# Generated by Django 6.0.7 on 2026-07-15 03:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('nacionalidad', models.CharField(blank=True, max_length=80, verbose_name='nacionalidad')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('biografia', models.TextField(blank=True, verbose_name='biografía')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('genero', models.CharField(max_length=80, verbose_name='género')),
                ('fecha_publicacion', models.DateField(verbose_name='fecha de publicación')),
                ('numero_paginas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número de páginas')),
                ('idioma', models.CharField(default='Español', max_length=40, verbose_name='idioma')),
                ('disponible', models.BooleanField(default=True, verbose_name='disponible')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='catalogo.autor', verbose_name='autor')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'ordering': ['titulo'],
            },
        ),
    ]
