# Generated by Django 6.0.7 on 2026-07-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_autor_foto_libro_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='imagen')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
    ]
